// Types autogenerated from: http://localhost:9695/actions/manage/isUsername/codegen
// (required: <app/> just graphql console)
import { ActionPayload } from "../ActionPayload";

type IsUsernameOutput = {
    exists: boolean
}

type isUsernameArgs = {
    username: string
}

export async function isUsername(action: ActionPayload<isUsernameArgs>): Promise<IsUsernameOutput> {
    const result = await action.request.db.GetUserByUsername(action.input);
    return { exists: result.users && result.users.length > 0 };
};
